name: 'Deploy to AWS S3'
description: 'Deploy the static built website to AWS S3 bucket'
inputs:
  bucket-name:
    description: 'The name of the S3 bucket to deploy to'
    required: true
  region-backet:
    description: 'The AWS region where the S3 bucket is located'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the built website files'
    required: true
runs:
  using: 'node20'
  main: 'main.js'